chef/chef-provisioning

lib/chef/provisioning/transport/ssh.rb

I did a bundle update today and got net-ssh 2.9.2 which causes a problem in forward_port. This patch fixes the problem for me, but I just noticed the whitespace is messed up :(

Fix forward_port when using net-ssh 2.9.2.

---

lib/chef/provider/machine.rb

Usability updates for my first time using chef-provisioning

---

lib/chef/provisioning/convergence_strategy/precreate_chef_objects.rb

Turns out we have the right code, but the server has a bug that cripples many installations.  Bug #292 has more detail on the workaround and issue.

Fix #59: set node permissions correctly before converging

---

lib/chef/provider/machine_batch.rb

Don't save after converge (that destroys attributes created by the converge)

---

Gemfile
chef-provisioning.gemspec

Dependency cleanup

---

CHANGELOG.md
lib/chef/provider/machine_batch.rb

fix machine_batch :destroy #319

---

lib/chef/provisioning/convergence_strategy/precreate_chef_objects.rb

fixes https://github.com/chef/chef-provisioning/issues/336
\cc @danielsdeleo @jkeiser 
I would rather not do a gsub, but this was a quick hack to get it working for me.  Is there some setting I can specify in `client.rb` on the remote machine that will make it ignore the `chefzero` part of the URL and just treat it like http?

Updating for newly introduced socketless mode

---

README.md

We just officially open sourced our driver

update readme with vsphere driver url

---

README.md

created a new PR to see if ICLA works for me.

change chef-provisioning-fog to chef-provisioning-aws in the AWS example

---

README.md

Makes the page a little noisy, but seems worthwhile.

Add gem version badges for core + drivers.

---

lib/chef/provider/load_balancer.rb
lib/chef/provider/machine.rb
lib/chef/provider/machine_image.rb
lib/chef/provisioning/driver.rb

This is an extension of https://github.com/chef/chef-provisioning/pull/424
\cc @jkeiser @randomcamel

Adding additional resource attributes for load_balancer and machine_image

---

lib/chef/provisioning/convergence_strategy/precreate_chef_objects.rb

Base the write options on the target node

Windows ohai hints, fixes #433

---

CHANGELOG.md
lib/chef/provisioning/version.rb

generating changelog with `github_changelog_generator -t d964f86065ada57e1f38b2bb0b0d7f0b9252898d  --future-release 1.4.1 --enhancement-labels "enhancement,Enhancement,New Feature" --bug-labels "bug,Bug,Improvement" chef/chef-provisioning --exclude-labels "Exclude From Changelog"`

Preparing to release 1.4.1

---

chef-provisioning.gemspec

Add gemspec files to allow bundler to run from the gem

---

lib/chef/provisioning/transport/ssh.rb

So super slow connections (like CI) can still work, fixes https://github.com/chef/chef-provisioning/issues/362
\cc @randomcamel @jkeiser

Making available? timeout use provided ssh_options, fixes #362

---

CHANGELOG.md
lib/chef/provisioning/version.rb

\cc @jkeiser @randomcamel @smith

Release preperation for 1.5.1

---

.travis.yml

\cc @pburkholder 
Fixes https://github.com/chef/chef-provisioning/issues/510

Trying to fix the Travis builds

---

lib/chef/provisioning/convergence_strategy/install_sh.rb

Add support for custom :install_sh_url

---

lib/chef/provider/machine_batch.rb

Addressing Issue #499: Wrapping the exceptions in machine_batch and adding the details of the machine

error handling for machine_batch resource

---

lib/chef/provisioning/convergence_strategy/precreate_chef_objects.rb

fixes https://github.com/chef/chef-provisioning-aws/issues/475

Fix WARN: nil is an invalid value for output_key_format

---

lib/chef/provisioning/transport/winrm.rb

fixes chef/chef-provisioning#516

set scheme to http if it was chefzero

---

chef-provisioning.gemspec

Signed-off-by: Lamont Granquist <lamont@scriptkiddie.org>

relax upper bounds on deps

---

chef-provisioning.gemspec
lib/chef/provisioning/transport/winrm.rb
lib/chef/provisioning/version.rb

Replaces https://github.com/chef/chef-provisioning/pull/552
Signed-off-by: tyler-ball <tyleraball@gmail.com>

Leverage winrm-elevated to execute chef install script

---

chef-provisioning.gemspec

Signed-off-by: Lamont Granquist <lamont@scriptkiddie.org>

allow cheffish 13.x

---

lib/chef/provisioning/transport/ssh.rb

Because of https://github.com/chef/chef/pull/6177

We can’t forward a socketless Zero server, so show a nice(ish) error

---

lib/chef/provisioning/machine/unix_machine.rb

add digest command to unix_machine.files_different?

---

README.md

Typo + small wording fix

---

README.md

This is the resolution to issue #587 "401 error on node \ client precreation"

Add options hash to 'with_chef_server' example 

---

.travis.yml
Gemfile

Signed-off-by: Tim Smith <tsmith@chef.io>

Test on Ruby 2.4.3 in Travis

---

chef-provisioning.gemspec

Signed-off-by: Lamont Granquist <lamont@scriptkiddie.org>

bump cheffish dep to allow 14.x

---

Gemfile
chef-provisioning.gemspec

Signed-off-by: Tim Smith <tsmith@chef.io>

Move dev deps into gemfile group

---

lib/chef/provisioning/machine/unix_machine.rb

Fix get_attributes for macOS machines
