chef/chef-provisioning

lib/chef/provider/load_balancer.rb

Generally, drivers shouldn't have to worry about edge cases like nil machine_specs.  It just causes a multiplicity of bugs.

Pass [] instead of nil when there are no machine specs

---

lib/chef/provisioning/convergence_strategy/install_sh.rb

As a Enterprise User I need to be able to tell chef-provisioning to use my corporate proxy so I can install chef client on my enterprise.
cc/ @jonsmorrow @mfdii @jkeiser @smford22

Install chef-client using Proxy

---

docs/providers/openstack.md

the fog driver is actually looking for the attribute `machine[:bootstrap_options][:key_path]` in order to load private key from the local machine

Adding documentation about the private key path

---

README.md

This is an update to the readme with instructions on how to fix the version conflict problem with ChefDK 0.4.0 locking chef-zero to 3.2.1 which conflicts with the requirement for version ~4.0 of the gem

Update chef gem to fix version conflict in ChefDK

---

chef-provisioning.gemspec
lib/chef/provisioning/transport/winrm.rb

bumping winrm dependency to avoid conflicts when using provisioner as a test-kitchen driver with new test-kitchen winrm functionality

bumping winrm dependency to 1.3.0

---

docs/examples/vagrant_linux.rb

If with_driver is not specified, trying to use this recipe with a machine resource will result in a RuntimeError:
```
Driver not specified for machine mario
```
Where "mario" is from the "simple" recipe example in this repository.

with_driver must be specified

---

CHANGELOG.md
lib/chef/provisioning/transport/ssh.rb

In one of our SSH provisioning scenarios, `/tmp` is not a valid location for `scp` to upload files to on the target machine. I've added a new option, `options[:scp_temp_dir]` which can be used to specify a different destination directory. This solves the problem for us.
````
with_machine_options :transport_options => {
...
:options => {
...
:scp_temp_dir => '/bootflash', # upload files to /bootflash instead of /tmp
},
...
}
````

Add options[:scp_temp_dir] to set a SCP destination other than /tmp

---

lib/chef/provider/machine.rb

Currently `from_image` is added to the `machine_spec` immediately after `allocate_machine`. I'm not sure if that was by design. I can think of scenarios where one would want to know if the machine is being created from an image from allocate_machine. This is possible using this hack:
```ruby
case action_handler
when Chef::Provisioning::AddPrefixActionHandler # From machine_batch
machines = action_handler.action_handler.provider.new_resource.machines
this_machine = machines.select { |m| m.name == machine_spec.name}.first
this_machine.from_image
else # from machine
action_handler.provider.new_resource.from_image
end
```
This feels a bit evil.
This PR sets the `machine_spec.from_image` in the `machine` `load_current_resource` which also allows the value to be set just once instead of both …

expose machine_spec.from_image to allocate_machine

---

Gemfile
chef-provisioning.gemspec
lib/chef/provisioning/convergence_strategy/install_msi.rb
lib/chef/provisioning/convergence_strategy/install_sh.rb

closes #327, closes #300, closes #38
chef/mixlib-install is extracted from test-kitchen. It supports installing nightlies and prereleases, supports windows properly and doesn't use bash.

use mixlib-install to install from omnitruck

---

chef-provisioning.gemspec

@tyler-ball should fix the uninitialized version number problem.

bump mixlib-install version

---

.travis.yml
bin/generate_driver
chef-client-version.gemfile
chef-provisioning.gemspec

Head-of-master fails on `rake install` for no discernible reason, but the specs pass.

Run our tests in a matrix of Chef client versions.

---

lib/chef/provider/load_balancer.rb
lib/chef/provider/machine.rb

This is to support https://github.com/chef/chef-provisioning-aws/pull/299
To make tagging cleaner I wanted to enable users to use `aws_tags` as a resource attribute instead of having to specify it in the `machine_options`.  This brings `machine` in line with other aws resources.
If we like this I'll have to expand it to the `load_balancer` resource as well.  The other option is that we continue having users specify `aws_tags` in the `machine_options` until we refactor away driver.rb

Specify additional machine_options from the resource attributes

---

lib/chef/provisioning/convergence_strategy/install_msi.rb
lib/chef/provisioning/machine/windows_machine.rb
lib/chef/provisioning/transport/winrm.rb

* Introduce the ability to run a cmd directly in winrm, rather than
through powershell
* Arrange for the output of the install script to be streamed
Fixes #409, Fixes chef/chef-provisioning-aws#284
cc @rancohen1 @tyler-ball (This supercedes #409 and should be more robust)

Upload the PS1 script and run directly

---

lib/chef/provisioning/convergence_strategy/install_sh.rb

While trying to provision a machine using chefdk I wondered why the usual chef-client package was installed instead. The `install_sh_arguments` is not passed to the `install_sh_path` call in https://github.com/chef/chef-provisioning/blob/master/lib/chef/provisioning/convergence_strategy/install_sh.rb#L45 - This PR wraps the call into a string, hence to single quotes inside the double quotes.

Added missing arguments to call of chef install shell script.

---

README.md

\cc @charlesjohnson @randomcamel 
We are deprecating support for chef-provisioning-(lxc|hanlon) and marking them as `maintainers wanted`.  Anyone interested in picking up maintainence should contact us on the chef-provisioning [gitter](https://gitter.im/chef/chef-provisioning).

Marking lxc and hanlon as seeking maintainers

---

lib/chef/provisioning/convergence_strategy/install_sh.rb

The conversion to `mixlib-install` left the passing of `install_sh_arguments` unwired.   This patch properly wires it up, and undoes https://github.com/chef/chef-provisioning/pull/439 which didn't work.

Fix install_sh_arguments passing after the conversion to mixlib-install

---

README.md
lib/chef/provisioning/convergence_strategy/precreate_chef_objects.rb

As discussed with @irvingpop , this adds the ability to specify the `no_proxy` option in the client.rb file when `convergence_options[:bootstrap_no_proxy]` is set (as a comma-seperated string).
This is useful when an environment needs to connect to some servers via a proxy (ie chef.io to download the chef-client), but others directly (ie internal infrastructure management API).

Added bootstrap_no_proxy support

---

chef-provisioning.gemspec

We are doing some work on mixlib-install to extend its functionality and we will be making some compat breaking changes. E.g. chef/mixlib-install#11
We would like to pin it more strictly here until we get the mixlib-install to 1.0.0 stage.

Pin mixlib-install more strictly.

---

chef-provisioning.gemspec
lib/chef/provisioning/convergence_strategy/install_sh.rb

This version won't re-install chef if you specify the chef_version convergence option.  Fixes https://github.com/chef/chef-provisioning/issues/428

Pinning to mixlib-install 0.7.0 until 1.0 is out

---

lib/chef/provisioning/transport/winrm.rb

This mimics the behavior of the `mkdir -p` line in the SSH transport.

Ensure target directory exists when using write_file with WinRM

---

lib/chef/provisioning/driver.rb

When monkeypatching the ResourceBuilder class we first need to ensure the primary instance is already defined.  Otherwise our monkeypatching becomes the primary instance and the real instance is never defined.
\cc @jkeiser @smith @randomcamel @jaym @btm

Require ResourceBuilder file before monkeypatching to ensure it is already defined

---

Gemfile
chef-provisioning.gemspec
lib/chef/provisioning/transport/ssh.rb

All the products in the ChefDK are getting updated to 3.0.2

Updating to the latest release of net-ssh to consume net-ssh/net-ssh#280

---

README.md
lib/chef/provisioning/transport/ssh.rb

In my environment I have a private cloud where I can spin up new VMs with no public network access nor access to the company git repos.  With the changes in this PR I can run a squid proxy on my workstation and forward that out to each VM for http proxy. I also forward out a remote port for our git server.
These changes work pretty well for me, but I'm curious what you all think.

Custom port forwards.

---

Rakefile
lib/chef/provider/machine.rb

The code used to fix provisioning for Cheffish 2.x broke `with_chef_server` in Cheffish 1.x, which did that by using the `machine` resource as the ChefNode provider's `new_resource` (since they have the same attributes). This reverts us to using the provider instead of the resource to take advantage of that.

Fix Provisioning with Cheffish 1.x

---

chef-provisioning.gemspec

Folks I work with need to use https://rubygems.org/gems/akamai-edgegrid.
Based on the releases, no one should be using 2.0.0 or 2.0.1 of inifile, hence the constraint.

Allow newer inifile gem

---

lib/chef/provisioning/convergence_strategy/install_cached.rb
lib/chef/provisioning/convergence_strategy/install_sh.rb

Using :client_rb_path convergence option make install_sh and install_cached convergence strategies trigger chef-client using -c flag pointing at this location where client.rb was created.

install_sh and install_cached convergence strategies trigger chef-client with -c flag

---

lib/chef/provisioning/transport/winrm.rb

\cc @chef/provisioning 
Cleans up the warning `WARN  WinRM::WinRMWebService : WinRM::WinRMWebService#run_powershell_script is deprecated. Use WinRM::CommandExecutor#run_powershell_script instead`

Cleaning up a deprecation warning

---

README.md

This was somewhat confusing before, seeming like the call to
with_chef_server should be added to the knife.rb. This is to fix #476.

Clarify where to put the call to `with_chef_server`

---

lib/chef/provider/machine_execute.rb
lib/chef/resource/machine_execute.rb

Add :timeout attribute to machine_execute resource that will set :timeout option in Chef::Provisioning::Transport.

Allow machine_execute resource to run commands that last longer then 15 minutes

---

chef-provisioning.gemspec
lib/chef/provisioning/convergence_strategy/install_msi.rb
lib/chef/provisioning/transport/winrm.rb

This PR accomplishes 3 things:
* Updates WinRM gem usage to 2.0 API
* Replaces file upload code with wintm-fs (same code used by test-kitchen, inspec and vagrant) with its 1.0 implementation its orders of mafnitude faster the the former implementation and no longer constrained to 8k chunks.
* Use one powershell based shell throughout an entire converge. This is simpler, faster and follows the same approach as test-kitchen.

Use Winrm v2 and let winrm-fs do file uploads

---

README.md

I wasted quite some time trying to understand how to fix properly the `chef_client[mymachine] had an error: Net::HTTPServerException: 403 "Forbidden"` error.
I stumbled accross the knife edit groups/admin.json solution before I was able to find the (outdated) blog post which put me on the way of the cleaner solution. I think we should rather document this in an obvious place

Add a section about ACLs in README.me

---

chef-provisioning.gemspec
lib/chef/provisioning/chef_run_data.rb
lib/chef/provisioning/recipe_dsl.rb
lib/chef/resource/machine_batch.rb

* driver_for_url needs a to_hash added to its config for the string url case (like used with vsphere, for exmple), since MergedConfig only takes hashes, but config is a mash
* resource creation functions no longer take caller
The first of these is actually required for chef12 with cheffish5 as well, the other two commits are chef-13 compatability

Fixes for chef13 and cheffish5.x/cheffish-13.x

---

Gemfile
chef-provisioning.gemspec

@lamont-granquist I thought I was being smart, but I think I just did not understand what you were doing in #577 and #568 
Am I correct in thinking that you have loosened these dependencies so they will work with upcoming Chef and ChefDK releases?

Putting back in place some development dependencies I removed

---

lib/chef/provisioning/convergence_strategy/install_cached.rb
lib/chef/provisioning/convergence_strategy/install_msi.rb
lib/chef/provisioning/convergence_strategy/install_sh.rb

After upgrading to the latest chef-dk (1.3.43) I was unable to chef-provision windows boxes in AWS.  Found the old open issue https://github.com/chef/chef-provisioning/issues/448 which was similar but I was also seeing this on the :setup action, and the error message is now different thanks to changes to the class since then...but I believe this would likely resolve that issue as well.
I was getting the message "Unable to converge locally via winrm. Local converge is currently only supported with SSH. You may only converge with winrm against a chef-server." It appeared that my `with_chef_server` config as well as my other `convergence_options` were being lost somewhere.
**Partial stack trace:**
```
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.2.1/lib/chef/provisioning/ …
```

Fix convergence_options being steamrolled rather than merged

---

lib/chef/provider/machine_file.rb

Implementing @joelwilson 's fix from https://github.com/chef/chef-provisioning/issues/285.
Attempting to set group/owner/mode on uploaded files bombs on Windows nodes with the message 
`set_attributes not overridden on Chef::Provisioning::Machine::WindowsMachine`
We should ignore this on windows nodes until implemented.

Ignore group/owner/mode attrs on Windows machine until implemented

---

chef-provisioning.gemspec

This changes remove the pessimistic constraint for mixlib-install.
Signed-off-by: Patrick Wright <patrick@chef.io>

remove normal pessimistic constraint for mixlib install

---

README.md
lib/chef/provisioning/transport/ssh.rb

We have situations where our templates have SSH port forwrding hard disabled - this patch allows the specifying of an SSH option to never even try.  It should alsop help with the "chef_server_url localhost" issue that crops up from time to time.

Add an option to never use SSH port forwardin

---

chef-provisioning.gemspec
lib/chef/provider/machine_execute.rb
lib/chef/provisioning/transport/ssh.rb

Machine execute was missing its provides, which is why it wasn't working with all providers, and now doens't work at all with newer chef.  add this back!

Fix machine execute

---

lib/chef/provisioning/transport/ssh.rb

The original code removes them from ssh_options entirely, whch persists through to a retry - change it to work on a copy

make ssh port forward options continue to work on retry

---

lib/chef/provisioning/transport/winrm.rb

Attempts to attach over winrm using SSL when the SSL endpoint does not
yet exist will result in an ECONNABORTED exception.
Obvious fix.
Fixes #605

Add Errno::ECONNABORTED to the list of rescued errors in the available? function

---

lib/chef/provisioning/convergence_strategy/install_sh.rb

Recently I faced with a problem where I needed to converge machine with custom recipe without affecting its run-list and node data.
By specifying custom parameters in machine options I managed to do that.
Please, see the actual usage of it:
'''
provision_config[:machine_options][:convergence_options][:chef_command] = 'chef-client -o recipe[sys_firewall::security_config]'
machine srv_name do
machine_options  provision_config[:machine_options]
chef_environment cluster
end
'''
Thanks.

Allow to pass custom parameters within machine resource to chef-client

---

README.md
lib/chef/provisioning/convergence_strategy/precreate_chef_objects.rb

This PR make it optionally do so.  Even worked once for me!

chef_config really should take a hash of options rather than a string

---

lib/chef/provisioning/machine/unix_machine.rb

Setting owner results in message "change group of..."
Updated to "change owner of..."

Fix typo in machine provisioning set_attributes

---

chef-provisioning.gemspec

No need to install these deep in the ruby gems install.
Signed-off-by: Tim Smith <tsmith@chef.io>

Don't ship the readme or changelog in the gem artifact

---

lib/chef/provider/machine.rb
lib/chef/provider/machine_batch.rb
lib/chef/resource/machine.rb
lib/chef/resource/machine_batch.rb

We had an issue where node search on a client was returning garbage, and spawning AWS machines when using chef-provisioning-aws for BAU operations.  To mitigate this, a ready_only action has been added, which will NEVER allocate a machine, just make it ready.  This is a peer to converge_only, and it would make sense to often run these together.

add ready_only action, to ONLY ready a machine but NEVER allocate it

---

chef-provisioning.gemspec

Allow version 5 of net-ssh, since it has a bunch of fixes which make newer systems work

Allow net ssh 5
